version: '3.8'

services:
    hackaton-app:
        build:
            dockerfile: Dockerfile.dev
        ports:
            - '3666:3666'
        environment:
            - DATABASE_URL=postgres://postgres:password@db:5432/mydb
            - PORT=3666
        depends_on:
            - hackaton-db
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules

    hackaton-db:
        image: postgres:latest
        environment:
            POSTGRES_DB: hackaton
            POSTGRES_USER: hackaton
            POSTGRES_PASSWORD: 12345
            PGUSER: hackaton
        ports:
            - '5432:5432'
        volumes:
            - postgres-app-data:/var/lib/postgresql/data

volumes:
    postgres-app-data:
